### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by ghost** [julienhau/skribblio-bot#1]
Hi, I have installed pillow but it says
>F:\Daten\Downloads\skribblio-bot-master>py skribblbot.py
>Traceback (most recent call last):
>  File "skribblbot.py", line 3, in <module>
>    from PIL import Image
>ModuleNotFoundError: No module named 'PIL'

Happens when I run the script

**Comment by julienhau** [comment]
> Hi, I have installed pillow but it says
> 
> > F:\Daten\Downloads\skribblio-bot-master>py skribblbot.py
> > Traceback (most recent call last):
> > File "skribblbot.py", line 3, in 
> > from PIL import Image
> > ModuleNotFoundError: No module named 'PIL'
> 
> Happens when I run the script

As mentioned in the readme, the script uses gui automation. It requires you to have the exact same monitor size as me. Thus, i dont think you will be able to use this script.
